<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>Mercurial Commit Message</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>\A(?!HG:)</string>
			<key>end</key>
			<string>(?=HG: Enter commit message)</string>
			<key>name</key>
			<string>meta.scope.message.hg-commit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\G</string>
					<key>end</key>
					<string>^(?!\G)</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>.{66,}$</string>
							<key>name</key>
							<string>invalid.illegal.line-too-long.hg-commit</string>
						</dict>
						<dict>
							<key>match</key>
							<string>.{51,}$</string>
							<key>name</key>
							<string>invalid.deprecated.line-too-long.hg-commit</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^(?=HG: Enter commit message)</string>
			<key>end</key>
			<string>\z</string>
			<key>name</key>
			<string>meta.scope.metadata.hg-commit</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#metadata</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>^(HG:)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.hg-commit</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.hg-prefix.hg-commit</string>
		</dict>
		<key>metadata</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(?=^HG: --)</string>
					<key>end</key>
					<string>(?!\G)((?=^HG:\w)|(?!^HG:))</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(^[ \t]+)?(?=HG:)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.whitespace.comment.leading.hg-commit</string>
								</dict>
							</dict>
							<key>contentName</key>
							<string>comment.line.hg-prefix.hg-commit</string>
							<key>end</key>
							<string>(?!\G)^</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\GHG:</string>
									<key>name</key>
									<string>punctuation.definition.comment.hg-commit</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(changed .*)$\n?</string>
									<key>name</key>
									<string>markup.changed.hg-commit</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(added .*)$\n?</string>
									<key>name</key>
									<string>markup.inserted.hg-commit</string>
								</dict>
								<dict>
									<key>match</key>
									<string>(removed .*)$\n?</string>
									<key>name</key>
									<string>markup.deleted.hg-commit</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.hg-commit</string>
	<key>uuid</key>
	<string>7B28C9A0-6D39-40FD-8C99-4DD8A0DE7DD4</string>
</dict>
</plist>
